# @package _global_

passes: 10

actor_rollout_ref:
  rollout:
    # Sampling parameters used during validation.
    val_kwargs:

      # Sampling temperature for rollout.
      temperature: 1

      # whether to repeat n times for validation
      n: ${passes}

      # Whether to sample during training rollout. False uses greedy sampling.
      do_sample: True